#!/bin/bash

# Path to the Forge arguments file generated by the installer
ARGS_FILE="libraries/net/minecraftforge/forge/1.20.1-47.4.9/unix_args.txt"

# Check if the file exists
if [ ! -f "$ARGS_FILE" ]; then
    echo "Error: Arguments file not found at $ARGS_FILE"
    echo "Make sure you have run the Forge installer: java -jar forge-installer.jar --installServer"
    exit 1
fi

echo "Reading JVM arguments from $ARGS_FILE..."

# Extract JVM arguments (lines before the main class)
JVM_ARGS=""
while read -r line; do
  # Stop reading when we reach the main class
  if [[ "$line" == "cpw.mods.bootstraplauncher.BootstrapLauncher" ]]; then
    break
  fi
  # Skip empty lines
  if [[ -z "$line" ]]; then
    continue
  fi
  # Append the line to JVM_ARGS
  JVM_ARGS="$JVM_ARGS $line"
done < "$ARGS_FILE"

echo "Starting ServerWrapper..."
# Run ServerWrapper with the extracted JVM arguments
# The module path and other settings are now passed to the JVM running ServerWrapper
java $JVM_ARGS -jar ServerWrapper.jar
